name: CMake
on: #Actions qui déclenchent les tests
  workflow_dispatch: # Créer un bouton manuel
  pull_request:
  push: # Lance les tests lors d'un push ou pullrequest sur master
    branches: 
      - master

env:
  # Customisation du type de build CMake (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs: #Liste des tests
  test:
    name: Running Units Tests
    # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment # Création d'un fichier à part pour les tests
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash # Utilisation d'un shell bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build # Essaie de construire l'application
      working-directory: ${{runner.workspace}}/build
      shell: bashù
      # Execute l'application. Possibilité de spécifier une cible avec "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute les tests définis par la configuration de CMake
      # https://cmake.org/cmake/help/latest/manual/ctest.1.html
      run: ctest -C $BUILD_TYPE
